### ISSUE TITLE
Some direction

### ISSUE THREAD

**Issue by kingb2019** [atridadl/cloudron-homeassistant-app#1]
Hi, I've tried installing this you the command line tooling and other ways and it is not working. On the command line, I keep getting a "404 message: No such app". Can you provide some direction on how to pull this app in?

**Comment by atridadl** [comment]
Sure. I haven't updated this app for quite some time actually so I will likely need to fix a couple of things.

**Comment by kingb2019** [comment]
Great, thank you! I’ll keep an eye here.

**Comment by atridadl** [comment]
Resolved in https://github.com/atridadl/cloudron-homeassistant-app/releases/tag/0.2.0
